### PR TITLE
phf_shared: make uncased feature compatible with no_std

### PR DESCRIPTION
**Pull request by petrosagg**

### CODE REVIEW

**Comment by benesch** [comment]
@JohnTitor would you be able to take a look at this?

**Review by JohnTitor — APPROVED** [review]
Oh sorry, I completely forgot to take a look at this PR after fixing CI. Thanks for the PR!

**Comment by benesch** [comment]
No no, no problem at all! Thanks for being such a responsive maintainer! :)

**Comment by petrosagg** [comment]
thank you!

**Comment by siedentop** [comment]
Hi Petros,

I just found this line, and was imagining that you'd like a ping on this.

@petrosagg: ` // FIXME(petrosagg): remove this once rust-phf/rust-phf#232 is released`

From https://github.com/chronotope/chrono-tz/blob/0dc2741ca8966818eea641004366d2aad2a7c686/chrono-tz-build/src/lib.rs#L113 

Best wishes and thanks for *chrono-tz*!

**Pull request merged**
